### ISSUE TITLE
getDataTCGA error with gene expression

### ISSUE THREAD

**Issue by elenapapaleo** [ELELAB/Moonlight2R#25]
after installation when I run from the vignette:
dataFilt <- getDataTCGA(cancerType = "LUAD", 
                          dataType = "Gene expression",
                          directory = "data",
                          nSample = 4)

I get this error:

Starting to add information to samples
 => Add clinical information to samples
 => Adding TCGA molecular information from marker papers
 => Information will have prefix 'paper_' 
luad subtype information from:doi:10.1038/nature13385
Error in method(object) : all assays must have the same nrow and ncol

The download works and the problem seems at the level of data aggregation (merging)

**Comment by mona-n** [comment]
There are two closed issues on TCGAbiolinks’ GitHub describing the same error you receive when you run getDataTCGA. Updating TCGAbiolinks seemed to solve the problem. I have TCGAbiolinks version 2.25.2 which works for me. 

https://github.com/BioinformaticsFMRP/TCGAbiolinks/issues/486
https://github.com/BioinformaticsFMRP/TCGAbiolinks/issues/475

**Comment by mtiberti** [comment]
fixed in #29 - in which we pinned the required `TCGAbiolinks` version to a recent one, to be sure this problem doesn't occur
